using MelonLoader;
using HarmonyLib;
using Il2CppScheduleOne;
using Il2CppScheduleOne.Economy;
using Il2CppScheduleOne.GameTime;
using Il2CppScheduleOne.NPCs;
using Il2CppScheduleOne.Product;
using Il2CppSystem.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

using Entry = Il2CppScheduleOne.Product.ProductList.Entry;

[assembly: MelonInfo(typeof(RevealCounterChance.EntryPoint), "RevealCounterChance", "1.0.0", "Johnny Johnny")]

namespace RevealCounterChance
{
    public class EntryPoint : MelonMod
    {
        public HarmonyLib.Harmony harmony;
        
        public override void OnInitializeMelon()
        {
            harmony = new HarmonyLib.Harmony("com.johnnyjohnny.revealcounterchance");
            harmony.PatchAll();
        }
        
        
        // This code is generated by DeepSeek based on the origina EvaluateCounteroffer function
        // I'm gonna be honest, I really couldn't be bothered to go through the whole thing and reverse everything to 
        // make it work correctly, so I got our lovely LLM overloads to do it for me.
        public static float EvaluateCounterofferPercentage(ProductDefinition product, int quantity, float price, Customer customer)
        {
            float adjustedWeeklySpend = customer.customerData.GetAdjustedWeeklySpend(customer.NPC.RelationData.RelationDelta / 5f);
            List<EDay> orderDays = customer.customerData.GetOrderDays(customer.CurrentAddiction, customer.NPC.RelationData.RelationDelta / 5f);
            float num = adjustedWeeklySpend / orderDays.Count;

            // Immediate rejection based on price threshold
            if (price >= num * 3f)
                return 0f;

            float valueProposition = Customer.GetValueProposition(
                Registry.GetItem<ProductDefinition>(customer.OfferedContractInfo.Products.entries[0].ProductID),
                customer.OfferedContractInfo.Payment / customer.OfferedContractInfo.Products.entries[0].Quantity
            );
            float productEnjoyment = customer.GetProductEnjoyment(product, customer.customerData.Standards.GetCorrespondingQuality());
            float num2 = Mathf.InverseLerp(-1f, 1f, productEnjoyment);
            float valueProposition2 = Customer.GetValueProposition(product, price / quantity);
            float num3 = Mathf.Pow(quantity / (float)customer.OfferedContractInfo.Products.entries[0].Quantity, 0.6f);
            float num4 = Mathf.Lerp(0f, 2f, num3 * 0.5f);
            float num5 = Mathf.Lerp(1f, 0f, Mathf.Abs(num4 - 1f));

            // High value proposition leads to acceptance
            if (valueProposition2 * num5 > valueProposition)
                return 100f;

            // Low value proposition leads to rejection
            if (valueProposition2 < 0.12f)
                return 0f;

            float num6 = productEnjoyment * valueProposition;
            float num7 = num2 * num5 * valueProposition2;

            // Better product enjoyment and proposition leads to acceptance
            if (num7 > num6)
                return 100f;

            float num8 = num6 - num7;
            float num9 = Mathf.Lerp(0f, 1f, num8 / 0.2f);
            float t = Mathf.Max(customer.CurrentAddiction, customer.NPC.RelationData.NormalizedRelationDelta);
            float num10 = Mathf.Lerp(0f, 0.2f, t);

            // Calculate probabilistic acceptance chance
            if (num9 <= num10)
                return 100f;
            if (num9 - num10 >= 0.9f)
                return 0f;

            float probability = (0.9f + num10 - num9) / 0.9f;
            return Mathf.Clamp(probability, 0f, 1f) * 100f;
        }
    }
    
    // This is horrendous
    // It should not be done on every update, but it really doesn't matter that much
    // It's a super simple fix, just make it happen on Open, ChangePrice, and ChangeQuantity
    [HarmonyPatch(typeof(Il2CppScheduleOne.UI.Phone.CounterofferInterface))]
    [HarmonyPatch("Update")]
    class CounterOfferUpdatePatch
    {
        static void Postfix(Il2CppScheduleOne.UI.Phone.CounterofferInterface __instance)
        {
            Button confirmButton = __instance.ConfirmButton;
            Text confirmButtonText = confirmButton.GetComponentInChildren<Text>();

            float chance = EntryPoint.EvaluateCounterofferPercentage(__instance.selectedProduct, __instance.quantity, __instance.price, __instance.conversation.sender.GetComponent<Customer>());
            chance = Mathf.RoundToInt(chance);
            
            confirmButtonText.text = $"Send ({chance}%)";
        }
    }
}