using System;
using MelonLoader;
using HarmonyLib;
using ScheduleOne;
using ScheduleOne.Economy;
using ScheduleOne.GameTime;
using ScheduleOne.Product;
using System.Collections.Generic;
using System.Reflection;
using ScheduleOne.Messaging;
using UnityEngine;
using UnityEngine.UI;

[assembly: MelonInfo(typeof(RevealCounterChance.EntryPoint), "RevealCounterChance", "1.0.1", "Johnny Johnny")]

// This was made in like 30 minutes, please no judging thank you :)
namespace RevealCounterChance
{
    public class EntryPoint : MelonMod
    {
        public HarmonyLib.Harmony harmony;

        public static FieldInfo cachedCustomerDataField;
        public static FieldInfo cachedSelectedProductField;
        public static FieldInfo cachedQuanityField;
        public static FieldInfo cachedPriceField;
        public static FieldInfo cachedConversationField;
        
        public override void OnInitializeMelon()
        {
            harmony = new HarmonyLib.Harmony("com.johnnyjohnny.revealcounterchance");
            harmony.PatchAll();
            
            // Customer.customerData
            cachedCustomerDataField = typeof(Customer).GetField("customerData", BindingFlags.Instance | BindingFlags.NonPublic);
            
            cachedSelectedProductField = typeof(ScheduleOne.UI.Phone.CounterofferInterface).GetField("selectedProduct", BindingFlags.Instance | BindingFlags.NonPublic);
            
            cachedQuanityField = typeof(ScheduleOne.UI.Phone.CounterofferInterface).GetField("quantity", BindingFlags.Instance | BindingFlags.NonPublic);
            
            cachedPriceField = typeof(ScheduleOne.UI.Phone.CounterofferInterface).GetField("price", BindingFlags.Instance | BindingFlags.NonPublic);
            
            cachedConversationField = typeof(ScheduleOne.UI.Phone.CounterofferInterface).GetField("conversation", BindingFlags.Instance | BindingFlags.NonPublic);
            
            if (cachedCustomerDataField == null)
                throw new MissingFieldException("customerData field not found");
        }
        
        
        // This code is generated by DeepSeek based on the origina EvaluateCounteroffer function
        // I'm gonna be honest, I really couldn't be bothered to go through the whole thing and reverse everything to 
        // make it work correctly, so I got our lovely LLM overloads to do it for me.
        public static float EvaluateCounterofferPercentage(ProductDefinition product, int quantity, float price, Customer customer)
        {
            CustomerData customerData = (CustomerData)cachedCustomerDataField.GetValue(customer);
            
            float adjustedWeeklySpend = customerData.GetAdjustedWeeklySpend(customer.NPC.RelationData.RelationDelta / 5f);
            List<EDay> orderDays = customerData.GetOrderDays(customer.CurrentAddiction, customer.NPC.RelationData.RelationDelta / 5f);
            float num = adjustedWeeklySpend / orderDays.Count;

            // Immediate rejection based on price threshold
            if (price >= num * 3f)
                return 0f;

            float valueProposition = Customer.GetValueProposition(
                Registry.GetItem<ProductDefinition>(customer.OfferedContractInfo.Products.entries[0].ProductID),
                customer.OfferedContractInfo.Payment / customer.OfferedContractInfo.Products.entries[0].Quantity
            );
            float productEnjoyment = customer.GetProductEnjoyment(product, customerData.Standards.GetCorrespondingQuality());
            float num2 = Mathf.InverseLerp(-1f, 1f, productEnjoyment);
            float valueProposition2 = Customer.GetValueProposition(product, price / quantity);
            float num3 = Mathf.Pow(quantity / (float)customer.OfferedContractInfo.Products.entries[0].Quantity, 0.6f);
            float num4 = Mathf.Lerp(0f, 2f, num3 * 0.5f);
            float num5 = Mathf.Lerp(1f, 0f, Mathf.Abs(num4 - 1f));

            // High value proposition leads to acceptance
            if (valueProposition2 * num5 > valueProposition)
                return 100f;

            // Low value proposition leads to rejection
            if (valueProposition2 < 0.12f)
                return 0f;

            float num6 = productEnjoyment * valueProposition;
            float num7 = num2 * num5 * valueProposition2;

            // Better product enjoyment and proposition leads to acceptance
            if (num7 > num6)
                return 100f;

            float num8 = num6 - num7;
            float num9 = Mathf.Lerp(0f, 1f, num8 / 0.2f);
            float t = Mathf.Max(customer.CurrentAddiction, customer.NPC.RelationData.NormalizedRelationDelta);
            float num10 = Mathf.Lerp(0f, 0.2f, t);

            // Calculate probabilistic acceptance chance
            if (num9 <= num10)
                return 100f;
            if (num9 - num10 >= 0.9f)
                return 0f;

            float probability = (0.9f + num10 - num9) / 0.9f;
            return Mathf.Clamp(probability, 0f, 1f) * 100f;
        }
    }
    
    [HarmonyPatch(typeof(ScheduleOne.UI.Phone.CounterofferInterface))]
    class CounterofferInterfacePatches
    {
        private static void UpdateConfirmButtonText(ScheduleOne.UI.Phone.CounterofferInterface instance)
        {
            Button confirmButton = instance.ConfirmButton;
            Text confirmButtonText = confirmButton.GetComponentInChildren<Text>();
            
            ProductDefinition productDefinition = (ProductDefinition)EntryPoint.cachedSelectedProductField.GetValue(instance);
            int quantity = (int)EntryPoint.cachedQuanityField.GetValue(instance);
            float price = (float)EntryPoint.cachedPriceField.GetValue(instance);
            MSGConversation conversation = (MSGConversation)EntryPoint.cachedConversationField.GetValue(instance);
        
            float chance = EntryPoint.EvaluateCounterofferPercentage(
                productDefinition,
                quantity,
                price,
                conversation.sender.GetComponent<Customer>()
            );
        
            confirmButtonText.text = $"Send ({Mathf.RoundToInt(chance)}%)";
        }

        [HarmonyPatch("Open")]
        [HarmonyPostfix]
        static void PostOpenPatch(ScheduleOne.UI.Phone.CounterofferInterface __instance)
        {
            UpdateConfirmButtonText(__instance);
        }

        [HarmonyPatch("ChangePrice")]
        [HarmonyPostfix]
        static void PostPriceChangePatch(ScheduleOne.UI.Phone.CounterofferInterface __instance)
        {
            UpdateConfirmButtonText(__instance);
        }

        [HarmonyPatch("ChangeQuantity")]
        [HarmonyPostfix]
        static void PostQuantityChangePatch(ScheduleOne.UI.Phone.CounterofferInterface __instance)
        {
            UpdateConfirmButtonText(__instance);
        }
    }
}